#!/usr/bin/env node

require('babel-polyfill')

const { spawn } = require('child_process')
const { env } = require('decentraland-commons')

let CONNECTION_STRING = process.env.CONNECTION_STRING

if (!CONNECTION_STRING) {
  env.load({ path: '../src/.env' })

  CONNECTION_STRING = env.get('CONNECTION_STRING', () => {
    throw new Error(
      'Please set a CONNECTION_STRING env variable before running migrations'
    )
  })
}

const child = spawn(
  './node-pg-migrate',
  [
    '--database-url-var',
    'CONNECTION_STRING',
    '--migrations-dir',
    '.',
    '--ignore-pattern',
    '\\..*|.*migrate',
    ...process.argv.slice(2)
  ],
  {
    env: { ...process.env, CONNECTION_STRING }
  }
)
console.log(`Running command "${child.spawnargs.join(' ')}"\n`)

child.on('error', function(error) {
  console.log(error.message)
})

child.stdout.on('data', function(data) {
  process.stdout.write(data.toString())
})

child.stderr.on('data', function(data) {
  process.stdout.write(data.toString())
})
