- hosts: backends
  remote_user: ubuntu

  tasks:
    - name: Base packages
      block:
        - name: Update packages
          apt:
            update_cache: yes
        - name: Upgrade packages
          apt:
            name: "*"
            state: latest
            force_apt_get: true
        - name: Autoremove packages
          apt:
            autoremove: yes
      become: yes
      become_method: sudo

    - name: Install nodejs
      block:
        - name: Get nodejs package  
          get_url: 
            url: https://deb.nodesource.com/setup_8.x
            dest: /tmp/nodesource_setup.sh
        - name: Update apt source
          shell: bash /tmp/nodesource_setup.sh
        - name: Update packages
          apt:
            update_cache: yes
        - name: Install nodejs
          apt:
            name: nodejs
            state: present
      become: yes
      become_method: sudo

    - name: Get application
      git:
        # TODO: setup repo location as variable
        repo: 'https://github.com/decentraland/marketplace.git'
        dest: /home/ubuntu/app
        version: chore/ansible-setup-server

        # TODO: Setup environment variables

    - name: Setup supervisor
      block:
        - name: Install supervisor
          apt:
            name: supervisor
            state: present
        - name: App config file
          copy:
            src: /home/ubuntu/app/etc/supervisor/mkt-app.conf
            dest: /etc/supervisor/conf.d
        - name: Monitor config file
          copy:
            src: /home/ubuntu/app/etc/supervisor/mkt-monitor.conf
            dest: /etc/supervisor/conf.d
      become: yes
      become_method: sudo
